version: '3'

networks:
  easily:
    external: true
services:
  mysql:
    container_name: mysql
    image: mysql:8
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: easily
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS easily;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      - easily

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - easily

  npm:
    container_name: npm
    image: node:current-alpine
    networks:
      - easily

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - easily
